7/save actions
graasp/graasp-plugin-actions pull request #10
Opened 2022-01-11 15:56 UTC by pyphilia

Reopen PR due to branch renaming.

2022-01-26 17:56 UTC, juancarlosfarah requested changes
Interesting commit! Did my best to try and follow everything that's happening. Added questions, comments, and suggestions.

2022-01-26 17:56 UTC, juancarlosfarah commented on src/index.ts
> +    const geo = geoip.lookup(request.ip);
We need to somehow allow this to be disabled.

2022-01-26 17:56 UTC, juancarlosfarah commented on src/services/action/base-action-task.ts
> +    this.status = 'NEW';
Factor this out?

2022-01-27 14:05 UTC, pyphilia commented on src/services/action/get-actions-task.ts
> +    this.status = 'OK';
Kind of, but it's only in graasp core. We plan to have a graasp-constants.. or in graasp-types to uniformize everything.

2022-01-27 14:06 UTC, pyphilia commented on src/db-service.ts
> +        ORDER BY RANDOM()
It's in case there's more actions than the sample we want to take. Wasn't it random in the old graasp?

2022-02-02 11:42 UTC, merged